name: SokoFresh API

on:
  push:
    branches:
      - develop

  # Run tests for any PRs.
  pull_request:

#Setup workflows to be tested sequentially
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | # To fetch all history for all tags and branches
          git fetch --prune --unshallow
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7

      #Task for installing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Task for linting with black
      - name: Lint with black
        run: |
          # Code formatting with black, check every python file in the app directory 
          black app 
          black --check app

      # Task for testing with pytest
      - name: Test with pytest
        env:
          DB_URI: ${{ secrets.DB_URI }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pytest
